name: Build 

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Select FR version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "((languageSelection}{)+(fr|en))"
          replace: "languageSelection}{fr"
          include: "resume.tex"
          regex: true
      - name: Compile FR Resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true
      - name: Rename FR PDF
        run: mv resume.pdf Resume-FR.pdf
        
      - name: Select EN version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "((languageSelection}{)+(fr|en))"
          replace: "languageSelection}{en"
          include: "resume.tex"
          regex: true
      - name: Compile EN document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true
      - name: Rename EN PDF
        run: mv resume.pdf Resume-EN.pdf
        
      - name: Install ghostscript
        run: sudo apt install ghostscript
      - name: Change ImageMagick security policy
        run: |
          DQT='"' 
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
      - name: Convert PDF to PNG
        run: |
          convert -density 90 -background white -alpha off Resume-FR.pdf Resume-FR.png -quality 90
          convert -density 90 -background white -alpha off Resume-EN.pdf Resume-EN.png -quality 90
        
      - name: Commit the new generated files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Resume-FR.pdf Resume-FR.png Resume-EN.pdf Resume-EN.png
          git commit -m "Generated new PDFs and PNGs"
      - name: Push Commit
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
